### ISSUE TITLE
Connect over implementation details

### ISSUE THREAD

**Issue by ntegrals** [xavierlu/sandwich-attack#1]
Hey Xavier,

I am currently working on my own implementation of the paper. 

If you are interested in connecting let me know. I think it would be mutually beneficial to talk about things such as priority gas auctions, game theoretic aspects and other implementation details.

**Comment by xavierlyu** [comment]
Hi,

Yes I am more than happy to collaborate and work on it together. Do you have telegram/facebook/discord/ etc.?

**Comment by ntegrals** [comment]
Great to hear that!

Discord works best - ntegral#8011.
